#!/usr/bin/env python3
"""Generate the Crimson Dark GTK4 theme (for plain-GTK4 apps like pavucontrol).

Recolours GTK's own built-in dark stylesheet, so every widget is covered:
neutral greys get a red tint at the same lightness, the blue accent family
becomes crimson, and status colours (green/orange/red) are left alone.
Re-run after a GTK4 upgrade:

    python3 gen-gtk4-crimson.py > ~/.local/share/themes/OB-Crimson-Dark/gtk-4.0/gtk.css
"""
import colorsys, re, sys
import gi
gi.require_version("Gtk", "4.0")
from gi.repository import Gio, Gtk  # noqa: F401  (importing Gtk registers its resources)

SRC = "/org/gtk/libgtk/theme/Default/Default-dark.css"
css = Gio.resources_lookup_data(SRC, 0).get_data().decode()

# Exact anchors onto the palette (SPEC.md section 4).
EXACT = {
    (0x15, 0x53, 0x9e): (0xc0, 0x30, 0x3a),  # selected / accent bg -> crimson
    (0x35, 0x84, 0xe4): (0xe5, 0x48, 0x4d),  # accent / links       -> accent hover
    (0x1f, 0x76, 0xe1): (0xe5, 0x48, 0x4d),
    (0xee, 0xee, 0xec): (0xe8, 0xd5, 0xd0),  # foreground
    (0x91, 0x91, 0x90): (0x9a, 0x7a, 0x7e),  # dim label
}
HUE = 353 / 360

def recolour(r, g, b):
    if (r, g, b) in EXACT:
        return EXACT[(r, g, b)]
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    if s < 0.08 or max(r, g, b) - min(r, g, b) < 8:        # neutral grey
        if l in (0.0, 1.0):
            return r, g, b
        s2 = 0.22 if l < 0.5 else 0.14
        nr, ng, nb = colorsys.hls_to_rgb(HUE, l, s2)
    elif 0.52 < h < 0.72:                                    # blue family
        nr, ng, nb = colorsys.hls_to_rgb(HUE, l, min(1.0, s * 0.9 + 0.1))
    else:                                                    # status colours
        return r, g, b
    return round(nr * 255), round(ng * 255), round(nb * 255)

def hex_sub(m):
    v = m.group(1)
    if len(v) == 3:
        v = "".join(c * 2 for c in v)
    r, g, b = (int(v[i:i + 2], 16) for i in (0, 2, 4))
    return "#%02x%02x%02x" % recolour(r, g, b)

def rgba_sub(m):
    fn, r, g, b, rest = m.group(1), *map(int, m.group(2, 3, 4)), m.group(5)
    nr, ng, nb = recolour(r, g, b)
    return f"{fn}({nr}, {ng}, {nb}{rest})"

# Assets are referenced relative to the stylesheet; point them back into GTK.
css = css.replace('url("assets/', 'url("resource:///org/gtk/libgtk/theme/Default/assets/')
css = re.sub(r"#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b", hex_sub, css)
css = re.sub(r"\b(rgba?)\(\s*(\d+),\s*(\d+),\s*(\d+)([^)]*)\)", rgba_sub, css)

sys.stdout.write(f"""/* Crimson Dark for plain GTK4 apps (pavucontrol), used via
   GTK_THEME=OB-Crimson-Dark. GENERATED by gen-gtk4-crimson.py from GTK
   {Gtk.get_major_version()}.{Gtk.get_minor_version()}.{Gtk.get_micro_version()}'s {SRC}; do not edit by hand. */

""")
sys.stdout.write(css)
sys.stdout.write("""

/* Exact palette surfaces on top of the recolour. */
window, window.background, dialog { background-color: #1a1012; color: #e8d5d0; }
.view, textview text, listview, list { background-color: #1f1416; color: #e8d5d0; }
notebook > header { background-color: #140c0d; }
""")
